packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - cpu-features
  - esbuild
  - lmdb
  - msgpackr-extract
  - protobufjs
  - sharp
  - ssh2
  - unrs-resolver
